spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pivotal?user=postgres&password=postgres

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
