spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    out-of-order: true
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/pivotal_test?user=postgres&password=postgres
