ruby:
  datasource:
    url: postgresql://postgres:postgres@postgres:5432/pivotal
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pivotal?user=postgres&password=postgres
server:
  port: 8080
frontend:
  url: http://localhost:8081